# Generated by Django 4.1 on 2023-09-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Music",
            fields=[
                ("valence", models.FloatField(null=True)),
                ("year", models.FloatField(null=True)),
                ("acousticness", models.FloatField(null=True)),
                ("artists", models.CharField(max_length=255, null=True)),
                ("danceability", models.FloatField(null=True)),
                ("duration_ms", models.FloatField(null=True)),
                ("energy", models.FloatField(null=True)),
                ("explicit", models.FloatField(null=True)),
                (
                    "id",
                    models.CharField(
                        max_length=255, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("instrumentalness", models.FloatField(null=True)),
                ("key", models.FloatField(null=True)),
                ("liveness", models.FloatField(null=True)),
                ("loudness", models.FloatField(null=True)),
                ("mode", models.FloatField(null=True)),
                ("name", models.CharField(max_length=255)),
                ("popularity", models.FloatField(null=True)),
                ("release_date", models.CharField(max_length=255, null=True)),
                ("speechiness", models.FloatField(null=True)),
                ("tempo", models.FloatField(null=True)),
            ],
            options={
                "db_table": "Music",
            },
        ),
    ]
