# Generated by Django 4.1 on 2023-09-06 05:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spotify", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="music",
            name="id",
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
